### PR TITLE
Refer directly to secrets without using Parameter Store

### PR DESCRIPTION
**Pull request by jamieparkinson**
This change means that we access/reference secrets directly in Secrets Manager, rather than by using the Parameter Store integration.

Whilst this is more verbose, it means that consumers can directly reference specific keys within secrets that are JSON objects - as this is a feature of Secrets Manager, not parameter store.

This change was necessary to access some of the secrets that already exist in the identity project.

### CODE REVIEW

**Review by kenoir — COMMENTED** [review]
Looks good - accessing individual elements inside a json formatted secret is a nice addition.

I'd consider making this backwards compatible somehow - adopting this change everywhere is quite onerous.

Can you add an example in the /example directory?

**Comment by alexwlchan** [comment]
> I'd consider making this backwards compatible somehow - adopting this change everywhere is quite onerous.

Is this breaking backwards compatibility? It looked to me like the external interface wouldn't change.

**Comment by jamieparkinson** [comment]
Yeah I couldn't really decide about this - @alexwlchan is right that the external interface wouldn't change, but on the other hand I wouldn't be surprised if something could get broken by it...

**Comment by kenoir** [comment]
> Is this breaking backwards compatibility? It looked to me like the external interface wouldn't change.

No - on review it's not - the removal of the SSM prefix threw me, but of course you don't need that if you're looking at secrets manager directly.

**Review by kenoir — APPROVED** [review]

**Pull request merged**
